### ISSUE TITLE
Fails to indent after a sass function

### ISSUE THREAD

**Issue by am** [AdamNiederer/ssass-mode#3]
I'm using this mode through vue-mode. Noticed this problem when editing a sass style block:

```html
<style lang="sass">

.foo
  color: transparentize(#000000, 0.5)$1
$2

</style>
```
After the sass function at `$1` when adding a new line it goes to the beginning of the next line `$2`. It was expected to indent same level of `color`. Also if a new property is added using tab to set/fix the indent does not work.

**Comment by danidoni** [comment]
Any news about this?

**Comment by AdamNiederer** [comment]
Hey, sorry, totally forgot about this one. Thankfully, it's an easy fix. Try 4b4ab4b86a52a17dedcce3f354aa75ba33b9ab2b once MELPA rebuilds - it should fix this issue.

Feel free to re-open this issue or file another one if you experience any further issues.

**Comment by am** [comment]
Tested and it works great! Many thanks @AdamNiederer
