### ISSUE TITLE
Add comment-start var for commenting in mmm-mode

### ISSUE THREAD

**Issue by srcrip** [AdamNiederer/ssass-mode#6]
PR: #5

We need to add `comment-start` to make comments work correctly in `mmm-mode` from what I can tell. There's a bunch of other variables too, but this was the bare minimum to at least make comments work out of the box in Sass sections of `mmm-mode` buffers.

**Comment by AdamNiederer** [comment]
Should be resolved - feel free to re-open if the issue persists!

**Comment by srcrip** [comment]
One more thing: https://github.com/AdamNiederer/ssass-mode/issues/8
